"""End-to-end example: a demographics-style summary table.

Builds a small "Table 14.1 -- Demographic Characteristics" style summary from a
pandas DataFrame, renders it to a real ``.rtf`` file, and verifies the output is
well-formed RTF (starts with ``{\\rtf1`` and has balanced group braces).

Run::

    python examples/demographics.py
"""

from __future__ import annotations

import os

import pandas as pd

from rtfreporter import (
    RtfDocument,
    as_rtftable,
    rtf_footer,
    rtf_header,
    style_body,
    style_header,
)

# A tidy "long" summary frame: one row per (Characteristic, Statistic) with a
# value per treatment arm.  This is the typical shape produced by a clinical
# summary step (e.g. an ARD / analysis-results dataset).
DEMOG = pd.DataFrame(
    {
        "Characteristic": [
            "Age (years)", "Age (years)", "Age (years)",
            "Sex", "Sex",
            "Race", "Race", "Race",
        ],
        "Statistic": [
            "n", "Mean (SD)", "Median",
            "Male", "Female",
            "White", "Black or African American", "Asian",
        ],
        "Placebo (N=42)": [
            "42", "54.3 (10.1)", "55.0",
            "20 (47.6%)", "22 (52.4%)",
            "30 (71.4%)", "8 (19.0%)", "4 (9.5%)",
        ],
        "Active (N=45)": [
            "45", "52.8 (9.7)", "53.0",
            "24 (53.3%)", "21 (46.7%)",
            "33 (73.3%)", "7 (15.6%)", "5 (11.1%)",
        ],
    }
)


def build() -> RtfDocument:
    # Merge the two hierarchy columns into a single indented clinical *stub*.
    table = as_rtftable(
        DEMOG,
        stub_vars=["Characteristic", "Statistic"],
        stub_label="",
        # Right-align the numeric summary columns; center their headers.
        col_spec=[
            {"col": 1, "align": "center"},
            {"col": 2, "align": "center"},
        ],
    )
    # Post-hoc styling verbs: bold, centered column headers.
    table = style_header(table, bold=True, align="center")
    table = style_body(table, cols=0, align="left")

    return (
        RtfDocument()
        .add_section(
            header=rtf_header([{"l": "Protocol XYZ-123", "r": "Page {AUTO_PAGE} of {AUTO_TOTAL_PAGES}"}]),
            footer=rtf_footer([{"l": "Confidential", "r": "Generated by rtfreporter"}]),
        )
        .add_table(
            table,
            title=["Table 14.1", "", "Demographic Characteristics", "(Intent-to-Treat Population)"],
            footnote=["Percentages are based on the number of subjects in each treatment arm."],
        )
    )


def main() -> str:
    doc = build()
    rtf = doc.to_rtf()

    assert rtf.startswith("{\\rtf1"), "output must start with {\\rtf1"
    assert rtf.count("{") == rtf.count("}"), "RTF group braces must balance"
    assert "Demographic Characteristics" in rtf

    out_path = os.path.join(os.path.dirname(__file__), "demographics.rtf")
    doc.save(out_path)
    print(f"Wrote {out_path} ({len(rtf):,} bytes, {rtf.count(chr(92) + 'row')} table rows)")
    return out_path


if __name__ == "__main__":
    main()
